config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: 'about'
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/edit' => 'customers#edit', as: 'customer_edit'
    patch 'customers' => 'customers#update', as: 'customer_update'
    get 'customers/check' => 'customers#check', as: 'customer_check'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'customer_withdraw'
    resources :addresses, only:[:index, :create, :edit, :update, :destroy]
    resources :items, only:[:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only:[:create, :index, :update, :destroy]
    post 'orders/check' => 'orders#check', as: 'order_check'
    get 'orders/thanks' => 'orders#thanks', as: 'order_thanks'
    resources :orders, only:[:new, :create, :index, :show]
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    resources :customers, only:[:index, :show, :edit, :update]
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :orders, only:[:index, :show, :update] do
      resources :order_details, only:[:update]
    end
  end

end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :address, presence: true
  validates :post_code, presence: true
  validates :telephone_number, presence: true

  def name
    last_name + " " + first_name
  end

  def name_kana
    last_name_kana + " " + first_name_kana
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end


  private

  def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:post_code,:address,:telephone_number,:email,:is_active)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-9 offset-2">
      <div class="customer-login-form">
        <h4><%= @customer.name %>さんの会員情報編集</h4>

        <div class="col-8 offset-2">
          <%= form_with model: @customer, url: admin_customer_path do |f| %>

            <div class="field my-3">
              <%= f.label :id, "会員ID"%>
              <%= @customer.id %>
            </div>

            <div class="field">
              <%= f.label "氏名" %><br/>
              <%= f.text_field :last_name, autofocus: true , class: "col-4 login-form-style mb-3 "%>
              <%= f.text_field :first_name, class: "col-4 login-form-style mb-3 ml-2" %>
            </div>

              <div class="field">
              <%= f.label "フリガナ" %><br/>
              <%= f.text_field :last_name_kana, class: "col-4 login-form-style mb-3" %>
              <%= f.text_field :first_name_kana, class: "col-4 login-form-style mb-3 ml-2"%>
            </div>

            <div class="field">
              <%= f.label :post_code,"郵便番号" %>
              <%= f.text_field :post_code, class: "col login-form-style mb-3" %>
            </div>

            <div class="field">
              <%= f.label :address,"住所" %>
              <%= f.text_field :address, class: "col login-form-style mb-3" %>
            </div>

            <div class="field">
              <%= f.label :telephone_number,"電話番号(ハイフンなし)" %>
              <%= f.text_field :telephone_number, class: "col login-form-style mb-3" %>
            </div>

            <div class="field">
              <%= f.label :email,"メールアドレス" %>
              <%= f.email_field :email,  autocomplete: "email", class: "col login-form-style mb-3" %>
            </div>

            <div class="field">
              <%= f.label :is_active, "会員ステータス" %>
              <%= f.radio_button :is_active,true, value: true  %>
              <%= f.label :is_active_true,"有効" %>
              <%= f.radio_button :is_active,false,value: false %>
              <%= f.label :is_active_false,"退会" %>
            </div>
            <div class="d-flex flex-row-reverse mt-3">
              <%= f.submit "変更を保存",class: "btn btn-success"%>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container admin-customer">
  <div class="row">
    <h4 class="my-3">会員一覧</h4>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">会員ID</th>
          <th scope="col">氏名</th>
          <th scope="col">メールアドレス</th>
          <th scope="col">ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td scope="row"><%= customer.id %></td>
            <td><%= link_to customer.name, admin_customer_path(customer.id) %></td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_active  %>
                <div class="text-success">有効</div>
              <% else %>
                <div class="text-muted">退会</div>
              <% end %>
            </td>
          </tr>
        <% end %>
        <td><%= paginate @customers %></td>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container admin-customer">
  <div class= "row">
    <h4 class="my-4"><%= @customer.name %>さんの会員詳細</h4>
    <table class="table">
      <tbody>
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>

        <tr>
          <th>氏名</th>
          <td><%= @customer.name %></td>
        </tr>

        <tr>
          <th>フリガナ</th>
          <td><%= @customer.name_kana %></td>
        </tr>

        <tr>
          <th>郵便番号</th>
          <td><%= @customer.post_code %></td>
        </tr>

        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>

        <tr>
          <th>電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>

        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>

        <tr>
          <th>会員ステータス</th>
          <td>
            <% if @customer.is_active  %>
              <div class="text-success">有効</div>
            <% else %>
              <div class="text-muted">退会</div>
            <% end %>
          </td>
        </tr>
        <td><%= link_to "編集する",edit_admin_customer_path(@customer.id),class: "btn btn-success my-3" %></td>
        <td><%= link_to "注文履歴一覧を見る", admin_orders_path,class: "btn btn-primary my-3" %></td>

      </tbody>
    </table>
  </div>
</div>