config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: 'about'
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/edit' => 'customers#edit', as: 'customer_edit'
    patch 'customers' => 'customers#update', as: 'customer_update'
    get 'customers/check' => 'customers#check', as: 'customer_check'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'customer_withdraw'
    resources :addresses, only:[:index, :create, :edit, :update, :destroy]
    resources :items, only:[:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only:[:create, :index, :update, :destroy]
    post 'orders/check' => 'orders#check', as: 'order_check'
    get 'orders/thanks' => 'orders#thanks', as: 'order_thanks'
    resources :orders, only:[:new, :create, :index, :show]
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    resources :customers, only:[:index, :show, :edit, :update]
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :orders, only:[:index, :show, :update] do
      resources :order_details, only:[:update]
    end
  end

end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { customer_payment: 0, payment_confirmed: 1, production: 2, preparation: 3, shipped: 4 }

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items,through: :order_details

  validates :post_code, presence: true
  validates :address, presence: true
  validates :postage, presence: true
  validates :name, presence: true
  validates :total_payment, presence: true

  def total_quantity
    order_details.inject(0) { |sum, item| sum + item.quantity }
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_total_price = @order.total_payment - @order.postage
    @order_details = @order.order_details.all
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    order_details = @order.order_details.all
    status = @order.status_before_type_cast
    if status == 1
      order_details.update_all(status: 1)
    end
    redirect_to request.referer
  end

  private
    def order_params
      params.require(:order).permit(:status)
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container admin-order">
  <div class="row">
    <h4 class="my-3">注文履歴一覧</h4>

    <table class="table">
      <thead>
        <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td>
              <%= link_to admin_order_path(order.id) do %>
                <%= l order.created_at %>
              <% end %>
            </td>
            <td><%= order.customer.name %></td>
            <td><%= order.total_quantity %></td>
            <td><%= order.status_i18n %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @orders %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
<h4>注文履歴詳細</h4>
<table class="table">
  <tbody>
    <tr>
      <th>購入者</th>
      <td><%= @order.customer.name %></td>
    </tr>
    <tr>
      <th>注文日</th>
      <td><%= l @order.created_at, format: :short %></td>
    </tr>
    <tr>
      <th>配送先</th>
      <td>
        〒<%= @order.post_code %><br>
        <%= @order.address %><br>
        <%= @order.name %>
      </td>
    </tr>
    <tr>
      <th>支払方法</th>
      <td><%= @order.payment_method_i18n %></td>
    </tr>
    <tr>
      <th>注文ステータス</th>
      <td>
        <%= form_with model:@order, url: admin_order_path(@order.id) do |f| %>
          <%= f.select :status, Order.statuses.keys.map {|status| [Order.statuses_i18n[status], status]} %>
          <%= f.submit "更新",class: "btn btn-success" %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
  <div class="row">
    <table class="table col-7">
      <thead>
        <tr>
          <th>商品名</th>
          <th>単価<br/>（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.price.to_s(:delimited) %></td>
            <td><%= order_detail.quantity %></td>
            <td><%= order_detail.sub_total.to_s(:delimited) %></td>
            <td>
              <%= form_with model:[@order, order_detail], url: admin_order_order_detail_path(@order.id, order_detail.id) do |f| %>
                <%= f.select :status, OrderDetail.statuses.keys.map {|status| [OrderDetail.statuses_i18n[status], status]} %>
                <%= f.submit "更新",class: "btn btn-success" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <table class="table col-4 ml-5">
      <tbody>
        <tr>
          <th>商品合計</th>
          <td><%= @order_total_price.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.postage.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>請求金額<br/>合計</th>
          <td><%= @order.total_payment.to_s(:delimited) %>円</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>