config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: 'about'
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/edit' => 'customers#edit', as: 'customer_edit'
    patch 'customers' => 'customers#update', as: 'customer_update'
    get 'customers/check' => 'customers#check', as: 'customer_check'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'customer_withdraw'
    resources :addresses, only:[:index, :create, :edit, :update, :destroy]
    resources :items, only:[:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only:[:create, :index, :update, :destroy]
    post 'orders/check' => 'orders#check', as: 'order_check'
    get 'orders/thanks' => 'orders#thanks', as: 'order_thanks'
    resources :orders, only:[:new, :create, :index, :show]
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    resources :customers, only:[:index, :show, :edit, :update]
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :orders, only:[:index, :show, :update] do
      resources :order_details, only:[:update]
    end
  end

end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="mb-5 py-3">
      <nav class="navbar navbar-expand-lg">
        <h2><strong><%= link_to "NaganoCake",root_path, class: "logo" %></strong></h2>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <div class="welcome">ようこそ、<%= current_customer.last_name %>さん！</div>
              <li>
                <%= link_to my_page_path, class: 'nav-text btn btn-outline-secondary' do %>
                  <i class="fas fa-user-circle"></i> マイページ
                <% end %>
              </li>
              <li>
                <%= link_to items_path, class: 'nav-text btn btn btn-outline-secondary' do %>
                  <i class="fas fa-cheese"></i> 商品一覧
                <% end %>
              </li>
              <li>
                <%= link_to cart_items_path, class: 'nav-text btn btn btn-outline-secondary' do %>
                  <i class="fas fa-shopping-cart"></i> カート
                <% end %>
              </li>
              <li>
                <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-text btn btn btn-outline-secondary' do %>
                  <i class="fas fa-sign-out-alt"></i> ログアウト
                <% end %>
              </li>
            <% elsif admin_signed_in? %>
              <li>
                <%= link_to admin_items_path, class: 'nav-text btn btn-outline-secondary' do %>
                  <i class="fas fa-cheese"></i> 商品一覧
                <% end %>
              </li>
              <li>
                <%= link_to admin_customers_path, class: 'nav-text btn btn btn-outline-secondary' do %>
                  <i class="fas fa-users"></i> 会員一覧
                <% end %>
              </li>
              <li>
                <%= link_to admin_orders_path, class: 'nav-text btn btn btn-outline-secondary' do %>
                  <i class="fas fa-history"></i> 注文履歴一覧
                <% end %>
              </li>
              <li>
                <%= link_to admin_genres_path, class: 'nav-text btn btn btn-outline-secondary' do %>
                  <i class="fas fa-cookie"></i> ジャンル一覧
                <% end %>
              </li>
              <li>
                <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-text btn btn btn-outline-secondary' do %>
                  <i class="fas fa-sign-out-alt"></i> ログアウト
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to about_path, class: 'nav-text btn btn-outline-secondary' do %>
                  <i class="fas fa-store"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to items_path, class: 'nav-text btn btn btn-outline-secondary' do %>
                  <i class="fas fa-birthday-cake"></i> 商品一覧
                <% end %>
              </li>
              <li>
                <%= link_to new_customer_registration_path, class: 'nav-text btn btn btn-outline-secondary' do %>
                  <i class="fas fa-user-plus"></i> 新規登録
                <% end %>
              </li>
              <li>
                <%= link_to new_customer_session_path, class: 'nav-text btn btn btn-outline-secondary' do %>
                <i class="fas fa-sign-in-alt"></i> ログイン
                <% end %>
              </li>
            <% end %>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer class="mt-5">
      <div class="container py-4">
        <div class="row py-2">
          <div class="mx-auto">
            <small>©️ NaganoCake </small>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>